apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serving-core.yaml
  - kourier.yaml
  - domainmapping.yaml
  - networking-certmanager.yaml
patchesStrategicMerge:
  - config-kourier-network.yaml
  - config-domains.yaml
  - config-autoscaler.yaml
  - config-certmanager.yaml
