apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: jubalzwolle.nl
spec:
  ref:
    name: jubalzwolle
    kind: Service
    apiVersion: serving.knative.dev/v1
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: www.jubalzwolle.nl
spec:
  ref:
    name: jubalzwolle
    kind: Service
    apiVersion: serving.knative.dev/v1